files:
  - source: /translations/en/LC_MESSAGES/messages.po
    translation: /translations/%two_letters_code%/LC_MESSAGES/%original_file_name%
  - source: README.rst
    translation: /%file_name%_%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        cs: en
        hu: en
        ru-UA: en
        de: en
  - source: CONTRIBUTING.rst
    translation: /%file_name%_%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        cs: en
        hu: en
        ru-UA: en
        de: en
